baseout: C:\Users\Ryan\Desktop\Data\pro
basein: C:\Users\Ryan\Desktop\Data\raw
params_file: None
#input: C:/Users/Ryan/Desktop/Data/raw/2019-11-27_mix_samples_graviprobe_2/raw/001_part1_mix_samples_graviprobe_2.avi
input: C:/Users/Ryan/Desktop/Data/raw/2019-12-03_data/raw/002_RT2_01_DII_12024_01.avi
output: 0
res_path: 0

tracker_control:
  views:
    new: True
    open: False
    tracks: True
  mode: manual

improcess:
  mode: find-all
  running: False
  fps: None
  pixel_size: 8.6 # microns
  size: None   # dimensions of image. [height, width, length]
  filter: sobel_focus
  max_track_len: 50
  kwargs:
    pre_filter: True
    focus_filter: False
    clearborder_filter: False
    img_thresh: 150
    edge_thresh: 30
    edge_dist: 1

matcher:
  err_threshold: 5000
  distance: 1
  area: 1
  squared: True

viewer:
  pos: [750, 50]
  scale: 0.5
