basein: C:\Users\Ryan\Desktop\Data\raw
baseout: C:\Users\Ryan\Desktop\Data\pro

input: C:\Users\Ryan\Desktop\002_RT2_01_DII_12024_00.avi
output: 0

tracker_control:
  views:
    new: True
    open: False
    tracks: True
  mode: manual
  
improcess:
  mode: find-all
  running: False
  fps: None
  pixel_size: 8.6 # microns
  size: None   # dimensions of image. [height, width, length]
  filter: sobel_focus
  max_track_len: 50
  kwargs:
    pre_filter: True
    focus_filter: False
    clearborder_filter: False
    img_thresh: 150
    edge_thresh: 30
    edge_dist: 1

matcher:
  error_threshold: 5000
  distance: 1
  area: 1
  squared: False

viewer:
  pos: [750, 50]
  scale: 0.5
