basein: C:\Users\Ryan\Desktop\Data\raw
baseout: C:\Users\Ryan\Desktop\Data\pro\por_graviprobe

input: C:\Users\Ryan\Desktop\Data\raw\2019-12-20_POR_graviprobe_trial2\000_por_graviprobe_trial2.avi
output: 0

improcess:
  mode: find-all
  running: False
  fps: None
  pixel_size: 8.6 # microns
  size: None   # dimensions of image. [height, width, length]
  filter: sobel_focus
  max_track_len: 50
  min_track_len: 3
  max_object_angle: 45
  n_frames: 40
  kwargs:
    pre_filter: True
    focus_filter: True
    clearborder_filter: True
    img_thresh: 100
    edge_thresh: 150
    edge_dist: 1

save:
  confirm: True # confirm save settings each time
  filename: props_frame_%05d.xlsx # name of object properties files
  save_frames: False
  clear: True # default clear after save

matcher:
  error_threshold: 5000
  distance: 1
  area: 1
  squared: False

viewer:
  pos: [750, 50]
  scale: 0.5
