site_name: Safas

theme:
      name: readthedocs
nav:
- Overview: 'index.md'
- Installation: 'installation.md'
- Use: 'use.md'
- Development: 'development.md'
- About:
    - 'License': 'about/license.md'
    - 'Notes': 'about/notes.md'
- FAQ: 'faq.md'
